packages:
  - 'packages/*'
  - 'packages/@swiftav/timeline'
  - 'packages/@swiftav/canvas'
  - 'packages/@swiftav/utils'
  - 'packages/@swiftav/history'
  - 'packages/@swiftav/media'
  - 'packages/@swiftav/project'
  - 'packages/@swiftav/audio'
  - 'packages/@swiftav/renderer'
  - 'packages/@swiftav/record'
